language: rust
sudo: false

addons:
  apt:
    packages:
      - gfortran

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose

after_success:
  - curl https://markov-chain.github.io/travis/after_success.sh | bash

env:
  global:
    secure: J8OMQgHgDljDy8GMn06pZJYcT2r9TYaUcDf8jQclu4/DBT4tmPou7BPdt2TKwRYx+M/9XUNT8KDwUJ9J/9n8G4W+hmLLAZ+QZYWz/EhStWPZeE5wgPREl6mpk7R9H3BVy1uXUgYMqN8bIgX98vyHTOqp12ciGK4H5FHlFc19w3c=

notifications:
  email: false
