language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://markov-chain.github.io/travis/documentation.sh | bash

env:
  global:
    - secure: TUxv3dB/fad18+/lApB8woFkPRV22EQmtgmFGYtyO056gT5806OnXFB97p3a4nSqx6A/k456x7iZsLIy9/7JgjGgdO2iw2HhF1ODZwnD4Ro4/ho+tDcNawaWJ56lxt/vaIC/Oc8gAIDYXOd2t2/o7/v688FL2FZXK9X9SEtaahE=

notifications:
  email: false
