[package]
name = "tempan"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[dependencies.hotspot]
git = "https://github.com/stainless-steel/hotspot"

[dependencies.matrix]
git = "https://github.com/stainless-steel/matrix"

[dev-dependencies.assert]
git = "https://github.com/stainless-steel/assert"
