[package]
name = "temperature"
version = "0.1.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/temperature"
homepage = "https://github.com/stainless-steel/temperature"
documentation = "https://stainless-steel.github.io/temperature"
description = """
The package provides an exponential-integrator-based solver for systems of
differential-algebraic equations modeling temperature of electronic systems.
"""

[dependencies]
hotspot = "*"
matrix = "*"
num = "*"

[dev-dependencies]
assert = "*"
rand = "*"
