[package]
name = "temperature"
version = "0.2.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/markov-chain/temperature"
homepage = "https://github.com/markov-chain/temperature"
documentation = "https://markov-chain.github.io/temperature"
description = """
The package provides an exponential-integrator-based solver for systems of
differential-algebraic equations modeling temperature of electronic systems.
"""

[dependencies]
hotspot = "*"
linear = "*"

[dev-dependencies]
assert = "*"
random = "*"
