[package]
name = "tempan"
version = "0.0.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/tempan"
homepage = "https://github.com/stainless-steel/tempan"
documentation = "https://stainless-steel.github.io/tempan"
description = """
The library provides an exponential-integrator-based solver for systems of
differential-algebraic equations modeling temperature of electronic systems.
"""

[dependencies]
hotspot = "0.0.2"
matrix = "0.0.2"

[dev-dependencies]
assert = "0.0.1"
